#!/usr/bin/env node
/**
 * Regenerates src/lib/labs.ts from the exercise repository's tiers.json.
 *
 * The exercise repository owns which chapters have an exercise and what kind.
 * This script copies that answer in, so a chapter page can link to its exercise
 * without 166 hand-written links going stale one at a time.
 *
 *   LABS_PATH=../atlas node scripts/sync-labs.mjs
 *
 * Run it with --check to fail instead of writing when the result would differ,
 * and note what it validates on the way: every slug claiming an exercise must be
 * a chapter that exists here. A rename on either side fails this rather than
 * shipping a link to a directory nobody created.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const labsPath = process.env.LABS_PATH ?? join(root, '..', 'atlas');
const docs = join(root, 'content/docs');
const checkOnly = process.argv.includes('--check');

/** Fumadocs drops parenthesised segments when building a slug: `(start-here)/preface` → `preface`. */
const slugOf = (segments) => segments.filter((segment) => !segment.startsWith('(')).join('/');

const chapterSlugs = async (dir = [], found = new Set()) => {
  for (const entry of await readdir(join(docs, ...dir), { withFileTypes: true })) {
    if (entry.isDirectory()) await chapterSlugs([...dir, entry.name], found);
    else if (entry.name.endsWith('.mdx')) found.add(slugOf([...dir, entry.name.slice(0, -4)]));
  }
  return found;
};

const tiers = JSON.parse(await readFile(join(labsPath, 'tiers.json'), 'utf8'));
const coded = Object.entries(tiers)
  .filter(([, tier]) => tier !== 'read')
  .sort(([a], [b]) => a.localeCompare(b));

const chapters = await chapterSlugs();
const unknown = coded.filter(([slug]) => !chapters.has(slug)).map(([slug]) => slug);
if (unknown.length) {
  console.error(`${unknown.length} slug(s) claim an exercise but are not chapters here:`);
  for (const slug of unknown) console.error(`  ${slug}`);
  process.exit(1);
}

const entries = coded.map(([slug, tier]) => `  '${slug}': '${tier}',`).join('\n');
const serialised = `/** Generated by scripts/sync-labs.mjs. Run \`npm run sync:labs\` rather than editing. */
import { labsGitConfig, labsUrl } from '@/lib/shared';

export type LabTier = 'build' | 'drill' | 'micro';

const TIERS: Record<string, LabTier> = {
${entries}
};

export function labFor(slug: string) {
  const tier = TIERS[slug];
  if (!tier) return null;

  return { tier, url: \`\${labsUrl}/tree/\${labsGitConfig.branch}/exercises/\${slug}\` };
}
`;

const target = join(root, 'src/lib/labs.ts');
const previous = await readFile(target, 'utf8').catch(() => null);

if (checkOnly) {
  if (previous !== serialised) {
    console.error('src/lib/labs.ts is stale — run `npm run sync:labs` and commit the result.');
    process.exit(1);
  }
  console.log(`src/lib/labs.ts current — ${coded.length} chapters with an exercise.`);
} else {
  await writeFile(target, serialised, 'utf8');
  console.log(`src/lib/labs.ts written — ${coded.length} chapters with an exercise.`);
}
